name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test_wheel:
    runs-on: macos-14
    steps:
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          branch: accelerate_whl
          workflow: wheels.yml
          name: cp311-macosx x86_64 openblas 10.9 
          repo: thalassemia/scipy
          run_number: 127
          workflow_conclusion: failure
      
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install and test
        run: |
          tee -a build_and_test.sh << END
          pip install pooch pytest pytest-xdist hypothesis pythran \
            array-api-strict pytest-timeout asv pytest-cov \
            scipy-1.14.0.dev0-cp311-cp311-macosx_10_9_x86_64.whl
          cd \$(python -c 'import os; import scipy; print(os.path.dirname(scipy.__file__))')/..
          pytest -n auto scipy
          END
          arch -x86_64 /bin/zsh ./build_and_test.sh
